import Foundation

/// TEMPLATE — do not edit this file with real values.
///
/// SETUP: Copy this file to `AppSecrets.swift` in the same folder, then
/// replace the placeholders with the Consumer Key and Consumer Secret
/// from an app you register at https://www.discogs.com/settings/developers
/// (use "Create an Application" — not the personal-access-token button).
///
/// `AppSecrets.swift` is gitignored so real credentials never get
/// committed. This `.example.swift` file is excluded from compilation in
/// project.yml so it doesn't clash with the real `enum AppSecrets`.
enum AppSecrets {
    static let discogsConsumerKey = "YOUR_DISCOGS_CONSUMER_KEY"
    static let discogsConsumerSecret = "YOUR_DISCOGS_CONSUMER_SECRET"

    static let userAgent = "VinylForAppleTV/0.1 +https://github.com/andreisudarikov19/vinyl-art-apple-tv"

    static var hasDiscogsCredentials: Bool {
        discogsConsumerKey != "YOUR_DISCOGS_CONSUMER_KEY" &&
        discogsConsumerSecret != "YOUR_DISCOGS_CONSUMER_SECRET" &&
        !discogsConsumerKey.isEmpty &&
        !discogsConsumerSecret.isEmpty
    }
}
